name: First PR

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  first-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: my-script
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const reply = github.rest.issues.listForRepo({
              state: 'all',
              creator: '${{ github.actor }}',
              repo: repo,
              owner: owner
            });
            const countPR = reply.data.filter((data) => data.pull_request).length;
            github.rest.issues.createComment({
              issue_number: context.issue.number
              repo: repo,
              owner: owner,
              body: 'Thanks so much for opening your first PR here!' + countPR
            });

