name: First PR

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  first-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: my-script
        with:
          script: |
            const [owner, repo] = '${{ github.repository }}'.split('/');
            const reply = github.rest.issues.listForRepo(context.repo({
              state: 'all',
              creator: context.payload.issue.user.login
            }));
            const countPR = reply.data.filter((data) => data.pull_request).length;
            github.rest.issues.createComment(context.issue({
              body: 'Thanks so much for opening your first PR here!' + countPR
            })

